language: php
cache:
  directories:
    - $HOME/.composer
sudo: false
matrix:
  fast_finish: true
  include:
    - php: '5.4'
    - php: '5.6'
    - php: '7.0'
    - php: '7.3'
install:
  - composer -n --no-ansi install --dev --prefer-source
