language: php
dist: trusty
cache:
  directories:
    - $HOME/.composer
sudo: false
matrix:
  fast_finish: true
  include:
    - php: '7.0'
    - php: '7.1'
    - php: '7.2'
    - php: '7.3'
    - php: '7.4'
before_install:
  # turn off XDebug
  - phpenv config-rm xdebug.ini
install:
  - composer install --no-progress --no-interaction --prefer-dist
